function rubiks(){var I='',Nb='\n--><\/script>',hb='" for "gwt:onLoadErrorFn"',fb='" for "gwt:onPropertyErrorFn"',Cb='"<script src=\\"',S='"><\/script>',U='#',Mb=');',Db='.cache.js\\"><\/scr" + "ipt>"',W='/',vb='1B2319A5FD9270CF3B6E39CDC2B032B4',wb='6A5828CB3A57D760CD1913CC18003D06',xb='6D522CBC8A841236F8D5788EBF1145D9',yb='94F8DAC1566FB47BA63E836FB82E84F4',R='<script id="',Eb='<script><!--\n',cb='=',V='?',zb='ADF8D86F59918A710E1BCCEC84BCDDF9',eb='Bad handler "',sb='Cross-site hosted mode not yet implemented. See issue ',Ab='DOMContentLoaded',T='SCRIPT',Q='__gwt_marker_rubiks',X='base',M='begin',L='bootstrap',Z='clear.cache.gif',bb='content',Lb='document.write(',P='end',Hb='evtGroup: "loadExternalRefs", millis:(new Date()).getTime(),',Jb='evtGroup: "moduleStartup", millis:(new Date()).getTime(),',pb='gecko',qb='gecko1_8',N='gwt.hybrid',gb='gwt:onLoadErrorFn',db='gwt:onPropertyErrorFn',ab='gwt:property',tb='http://code.google.com/p/google-web-toolkit/issues/detail?id=2079',ob='ie6',nb='ie8',Y='img',Bb='loadExternalRefs',$='meta',Gb='moduleName:"rubiks", sessionId:$sessionId, subSystem:"startup",',O='moduleStartup',mb='msie',_='name',jb='opera',J='rubiks',lb='safari',ub='selectingPermutation',K='startup',Ib='type: "end"});',Kb='type: "moduleRequested"});',rb='unknown',ib='user.agent',kb='webkit',Fb='window.__gwtStatsEvent && window.__gwtStatsEvent({';var k=window,l=document,m=k.__gwtStatsEvent?function(a){return k.__gwtStatsEvent(a)}:null,n,o,p=I,q={},r=[],s=[],t=[],u,v;m&&m({moduleName:J,sessionId:$sessionId,subSystem:K,evtGroup:L,millis:(new Date).getTime(),type:M});if(!k.__gwt_stylesLoaded){k.__gwt_stylesLoaded={}}if(!k.__gwt_scriptsLoaded){k.__gwt_scriptsLoaded={}}function w(){try{return k.external&&(k.external.gwtOnLoad&&k.location.search.indexOf(N)==-1)}catch(a){return false}}
function x(){if(n&&o){n(u,J,p);m&&m({moduleName:J,sessionId:$sessionId,subSystem:K,evtGroup:O,millis:(new Date).getTime(),type:P})}}
function y(){var e,f=Q,g;l.write(R+f+S);g=l.getElementById(f);e=g&&g.previousSibling;while(e&&e.tagName!=T){e=e.previousSibling}function h(a){var b=a.lastIndexOf(U);if(b==-1){b=a.length}var c=a.indexOf(V);if(c==-1){c=a.length}var d=a.lastIndexOf(W,Math.min(c,b));return d>=0?a.substring(0,d+1):I}
;if(e&&e.src){p=h(e.src)}if(p==I){var i=l.getElementsByTagName(X);if(i.length>0){p=i[i.length-1].href}else{p=h(l.location.href)}}else if(p.match(/^\w+:\/\//)){}else{var j=l.createElement(Y);j.src=p+Z;p=h(j.src)}if(g){g.parentNode.removeChild(g)}}
function z(){var b=document.getElementsByTagName($);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(_),g;if(f){if(f==ab){g=e.getAttribute(bb);if(g){var h,i=g.indexOf(cb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=I}q[f]=h}}else if(f==db){g=e.getAttribute(bb);if(g){try{v=eval(g)}catch(a){alert(eb+g+fb)}}}else if(f==gb){g=e.getAttribute(bb);if(g){try{u=eval(g)}catch(a){alert(eb+g+hb)}}}}}}
function C(a,b){var c=t;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function D(a){var b=s[a](),c=r[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(v){v(a,d,b)}throw null}
s[ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(jb)!=-1){return jb}else if(b.indexOf(kb)!=-1){return lb}else if(b.indexOf(mb)!=-1){if(document.documentMode>=8){return nb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return ob}}}}else if(b.indexOf(pb)!=-1){var d=/rv:([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){if(c(d)>=1008)return qb}return pb}return rb};r[ib]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};rubiks.onScriptLoad=function(a){rubiks=null;n=a;x()};if(w()){alert(sb+tb);return}y();z();m&&m({moduleName:J,sessionId:$sessionId,subSystem:K,evtGroup:L,millis:(new Date).getTime(),type:ub});var E;try{C([ob],vb);C([nb],vb);C([jb],wb);C([qb],xb);C([lb],yb);C([pb],zb);E=t[D(ib)]}catch(a){return}var F;function G(){if(!o){o=true;x();if(l.removeEventListener){l.removeEventListener(Ab,G,false)}if(F){clearInterval(F)}}}
if(l.addEventListener){l.addEventListener(Ab,function(){G()},false)}var F=setInterval(function(){if(/loaded|complete/.test(l.readyState)){G()}},50);m&&m({moduleName:J,sessionId:$sessionId,subSystem:K,evtGroup:L,millis:(new Date).getTime(),type:P});m&&m({moduleName:J,sessionId:$sessionId,subSystem:K,evtGroup:Bb,millis:(new Date).getTime(),type:M});var H=Cb+p+E+Db;l.write(Eb+Fb+Gb+Hb+Ib+Fb+Gb+Jb+Kb+Lb+H+Mb+Nb)}
rubiks();